const requisitionDefaults = {
  accountName: "",
  accountNumber: "",
  amountInWords: "",
  attentionTo: [],
  bankName: "",
  codes: "",
  countRef: 0,
  currency: "",
  date: null,
  holderCheck: {
    userId: "",
    email: "",
    name: "",
    signatureUrl: "",
  },
  hoderCheckDate: null,
  holderCheckDate: null,
  checkedBy: {
    email: "",
    name: "",
    photoUrl: "",
    signatureUrl: "",
  },
  reviewedBy: {
    email: "",
    name: "",
    photoUrl: "",
    signatureUrl: "",
  },
  reviewDate: null,
  checkedDate: null,
  approvedBy: {
    email: "",
    name: "",
    photoUrl: "",
    signatureUrl: "",
  },
  approvedDate: null,
  projectChargedTo: {
    account: {
      accountName: "",
      accountNumber: "",
      balance: "",
      bankName: "",
      id: "",
    },
    funder: "",
    id: "",
    projectName: "",
  },
  user: {
    userId: "",
    email: "",
    name: "",
    photoUrl: "",
    signatureUrl: "",
  },
  title: "",
  budgetLineItems: [
    {
      label: "",
      value: "",
    },
  ],
  invoices: [
    {
      id: "",
      name: "",
      url: "",
    },
  ],
  items: [
    {
      amount: 0,
      code: "",
      title: "",
    },
  ],
  projectName: "",
  pvNumber: 0,
  sourceAccountNumber: "",
  sourceBankName: "",
  status: "pending",
  step: 0,
  taxPercentage: "",
  taxable: "",
  time: null,
  total: "",
  type: "",
  userId: "",
  createdAt: null,
  retired: false,
  paid: false,
  serialNumber: 0,
  approvalCode: "",
};

export default requisitionDefaults;
